name: Build with Gradle
run-name: Go Go
on:
  push:
    branches:
      - production
      - 'releases/**'
jobs:
  build-with-gradle:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout production branch
      uses: actions/checkout@v3
      with:
        ref: production
          
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Where is here
      run: pwd
          
    - name: Executable Gradle
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew build
